<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test-domain-load-after-set-uncaught-exception-capture.html</title>
</head>
<body>

<script>
'use strict';
const common = require('../common');

process.setUncaughtExceptionCaptureCallback(common.mustNotCall());

common.expectsError(
  () => require('domain'),
  {
    code: 'ERR_DOMAIN_CALLBACK_NOT_AVAILABLE',
    type: Error,
    message: /^A callback was registered.*with using the `domain` module/
  }
);

process.setUncaughtExceptionCaptureCallback(null);
require('domain'); // Should not throw.

</script>

</body>
</html>
